apiVersion: postgresql.dev4devs.com/v1alpha1
kind: Database
metadata:
  namespace: ship-tracker-app
  name: ship-database
spec:
  size: 1
  databaseName: ship
  databaseCpu: 30m
  databaseCpuLimit: 60m
  databaseStorageRequest: 1Gi
  containerImagePullPolicy: Always
  databaseMemoryRequest: 128Mi
  configMapDatabasePasswordKey: QUARKUS_DATASOURCE_PASSWORD
  configMapDatabaseUserKey: QUARKUS_DATASOURCE_USERNAME
  configMapName: ship-tracker-database-credentials
  image: centos/postgresql-96-centos7
  databasePort: 5432
  databaseMemoryLimit: 512Mi
