apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    olm.providedAPIs: Backup.v1alpha1.postgresql.dev4devs.com,Database.v1alpha1.postgresql.dev4devs.com
  name: postgres-operator-group
  namespace: ship-tracker-app
spec:
  targetNamespaces:
  - ship-tracker-app
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/postgresql-operator-dev4devs-com.postgres: ""
  name: postgresql-operator-dev4devs-com
  namespace: ship-tracker-app
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: postgresql-operator-dev4devs-com
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: postgresql-operator.v0.1.1

