apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-shipdb
  namespace: ship-tracker-app
  labels:
    app.kubernetes.io/name: ship-tracker
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
