---
apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleJob
metadata:
  name: f5-update-dns-load-balancer
  namespace: ship-tracker-app
  labels:
    app.kubernetes.io/name: ship-tracker
spec:
  tower_auth_secret: toweraccess
  job_template_name: f5-update-dns-load-balancer
  extra_vars:
    APP_NAME: ship-tracker
    API_DOMAIN: demo.red-chesterfield.com
    # The AWS Route53 NS Record must exist with NameServers:
    # ns1.f5cloudservices.com
    # ns2.f5cloudservices.com
    GSLB_ZONE: www-apps
    BASE_DOMAIN: foxtrot.demo.red-chesterfield.com
